general {
    # Combined general settings

    # Matugen-generated border colors (keeping these as primary colors)
    col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
    col.inactive_border = rgba(595959aa)    

		# Border size (using the layout setting)
    border_size = 4

    # Gaps and layout settings
    gaps_in = 4
    gaps_out = 4
    gaps_workspaces = 0

    resize_on_border = false
    # no_focus_fallback = true
    layout = dwindle

    #focus_to_other_workspaces = true # ahhhh i still haven't properly implemented this
    allow_tearing = false

    # Snap configuration for floating windows
    snap {
        enabled = true        # Enable snapping for floating windows
        window_gap = 10       # Minimum gap in pixels between windows before snapping
        monitor_gap = 10      # Minimum gap in pixels between window and monitor edges before snapping
        border_overlap = false # If true, windows snap such that only one border's worth of space is between them
        respect_gaps = false   # If true, snapping will respect gaps between windows (set in general:gaps_in)
    }
}

misc {
    # background_color = rgba(10140fFF)
    force_default_wallpaper = 0 # Set to 0 or 1 to disable the anime mascot wallpapers
    disable_hyprland_logo = true # If true disables the random hyprland logo / anime girl background. :(

}


dwindle {
    pseudotile = true 		
		preserve_split = true # You probably want this
}

master {
    new_status = master
}

