input {
    # Keyboard: Add a layout and uncomment kb_options for Win+Space switching shortcut
    kb_layout = us,ara
    kb_options = grp:alt_shift_toggle
    numlock_by_default = true
    repeat_delay = 200
    repeat_rate = 35

    # touchpad {
    #     natural_scroll = yes
    #     disable_while_typing = true
    #     clickfinger_behavior = true
    #     scroll_factor = 0.5
    # }

    special_fallthrough = true
    follow_mouse = 1
		sensitivity = 0 
}

device {
    name = epic-mouse-v1
    sensitivity = -0.5
}
