render {
    cm_auto_hdr = 0
    expand_undersized_textures = true
    cm_auto_hdr = 1
    new_render_scheduling = true
    new_render_scheduling = false
    cm_auto_hdr = 0
    expand_undersized_textures = false
    new_render_scheduling = true
    cm_fs_passthrough = 1
    cm_enabled = true
    send_content_type = true
    cm_auto_hdr = 1
    direct_scanout = 2

}


